##TODO:
##     QA Checks for function(s): createGene2GO(), createAllGenes()
##     within function createGene2GO() fix retval assignment such that it no longer uses $ operator
##     within function createGene2Go() return the number of genes that are not assigned GO Terms
##     within function createGene2Go() creat a dataframe cataloging which genes do not have GO Terms
##     Write function validateTermMatching() to ensure thate each ensemble gene ID is correctly matched with GO Terms


source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("biomaRt")
biocLite("biomartr")
biocLite("GO.db")
biocLite("topGO")
biocLite("Rgraphviz")

library("biomaRt")
library("biomartr")
library("GO.db")
library("topGO")
library("Rgraphviz")


source("Directories.txt")
setwd(DEMasterDir)
load("DEanalysis.RData")

###########
##Functions
###########

##################################--createGene2GO()--#######################################
##Defines a function that returns a named list of character vectors linking Ensembl gene ID's to GO terms
##The output is formatted to be used as the 'gene2GO' parameter in the creation of a topGOdata obj
##Parameters: dataframe of DE expr. data containing a collumn corresponding to biomaRt attribute 'ensembl_gene_id'
##depends on biomaRT
##uses getBM() to get GOTerms via 'goslim_goa_accession' or 'go_id' attribute; potential caveate of reduced ('slim') GOTerm assignment
##Defaults to 'go_id'
createGene2GO <- function(DiffExpData, slim = FALSE){
  GO_Option = "go_id"
  if(slim == TRUE){
    GO_Option = "goslim_goa_accession"
  }

  ensembl = useMart("ensembl",dataset="hsapiens_gene_ensembl")
  
  message("Getting Gene Ontology Terms...")
  Go_Term_Table <- getBM(attributes = c("ensembl_gene_id", GO_Option), 
                   mart = ensembl, 
                   filters = "ensembl_gene_id", 
                   values = row.names(DiffExpData),
                   uniqueRows = TRUE,
                   verbose = FALSE)
  
  message(paste(length(Go_Term_Table[Go_Term_Table == ""]), "terms returned empty"))
  
  ##set any missing values to NA
  Go_Term_Table[Go_Term_Table == ""] <- NA
  Go_Term_Table <- Go_Term_Table[complete.cases(Go_Term_Table),]
  
  message(paste(length(Go_Term_Table[,1]), "complete terms aquired"))
  
  message("generating gene-to-GOs as list of character vectors...")
  retVal <- sapply(row.names(DiffExpData),
    function(x){
        Go_Term_Table[,GO_Option][grep(x, Go_Term_Table$ensembl_gene_id)]
    }, 
    USE.NAMES = TRUE
    )
  
  message("done.")
  return(retVal)
}

###################################--createAllGenes()--######################################
##Defines a function that returns a named vector linking Ensembl gene ID's to the BH adjusted P-value generated by DEseq2 DE analysis
##The output is formatted to be used as the 'allGenes' parameter of a topGOdata obj
##Parameter: dataframe 'DiffExpData' of DE expr. data with row.names(DiffExpData) = 'ensembl_gene_id' AND
##           containing collumn with BH adjusted P-values called padj
##uses BH adjusted p-value as the 'score' for topGO analysis 
createAllGenes <- function(DiffExpData){
  geneList <- resSig$padj
  names(geneList) <- row.names(resSig)
  message("performing QA checks...")
  
  message("done.")
  return(geneList)
}

#################################--ValidateTermMatching()--######################################


####################################
#topGO: create the topGO data object
####################################

## generate 'gene2GO' parameter of topGodata obj
geneID2GO <- createGene2GO(resSig)

##generate 'allGenes' parameter of topGOdata obj
geneList <- createAllGenes(resSig)

## assign new topGOdata object
GOdata <- new("topGOdata",
              description = "Matched study of irradiated vs non-irradiated patient nevi",
              ontology = "BP",
              allGenes = geneList, geneSel = function(scores){return(scores < 0.1)},
              annot = annFUN.gene2GO,
              gene2GO = geneID2GO)

############################
#Run topGO statistical tests
############################

resultFisher <- runTest(GOdata, algorithm = "classic", statistic = "fisher")

resultKS <- runTest(GOdata, algorithm = "classic", statistic = "ks")
resultKS.elim <- runTest(GOdata, algorithm = "elim", statistic = "ks")

##################################
##Data analysis and representation
##################################

allRes <- GenTable(GOdata, classicFisher = resultFisher,
                     classicKS = resultKS, elimKS = resultKS.elim,
                     orderBy = "elimKS", ranksOf = "classicFisher", topNodes = 20)

pValue.classic <- score(resultKS)
pValue.elim <- score(resultKS.elim)[names(pValue.classic)]
gstat <- termStat(GOdata, names(pValue.classic))
gSize <- gstat$Annotated / max(gstat$Annotated) * 4
gCol <- colMap(gstat$Significant)
plot(pValue.classic, pValue.elim, xlab = "p-value classic", ylab = "p-value elim",
       pch = 19, cex = gSize, col = gCol)


showSigOfNodes(GOdata, score(resultKS.elim), firstSigNodes = 10, useInfo = 'all')
